### ISSUE TITLE
training neural network

### ISSUE THREAD

**Issue by ghost** [taliegemen/Neural-Network-Adaptive-PID-Controller#1]
your work was so helpful to me, would you please put the MLP_Ann training code?

**Comment by taliegemen** [comment]
Hello, this can help [ANN-Training-on-MATLAB](https://github.com/alkimgokcen/Artificial-Neural-Network-Traning-on-MATLAB).
Best!

**Comment by ghost** [comment]
thank you very much. wish you all the best🙏
