### ISSUE TITLE
[Neural-Network-Adaptive-PID-Controller]

### ISSUE THREAD

**Issue by vedat-can** [taliegemen/Neural-Network-Adaptive-PID-Controller#3]
[Neural-Network-Adaptive-PID-Controller](https://github.com/taliegemen/Neural-Network-Adaptive-PID-Controller) merhaba bu uygulamanızı matlab eski sürümler için de paylaşabilir misiniz bende 2018 var açamıyorum maalesef. Yardımcı olursanız sevinirim teşekkürler

**Comment by taliegemen** [comment]
Merhaba,
Soru için teşekkür ederim, simulink kodunu daha önceki bir MATLAB versiyonuna uyarlamak mümkün olsa bile (ki olmayabilir) çok zaman alacağından planlarımda olmayan bir değişiklik.
Ek olarak gerekli MATLAB sürüm bilgisini readme dosyasına ekledim.
